var TABLE_HEADERS={
'Patients':['PatientID','MRN','PatientName','MobileNumber','Specialty','Consultant','CreatedBy','CreatedAt','ModifiedBy','ModifiedAt'],
'Arrival Records':['VisitID','VisitDate','ArrivalTime','PatientName','MRN','Room','Specialty','Consultant','Diagnosis','MedicationID','DoseNumber','FirstDose','PrimaryNurse','ArrivalStatus','TreatmentStatus','LabsStatus','ConsentStatus','SickLeave','WatcherLeave','HomeMedicationRefill','NextAppointmentDate','Notes','PatientID','CreatedBy','CreatedAt'],
'Visit Log':['VisitID','VisitDate','ArrivalTime','PatientName','MRN','Room','Specialty','Consultant','Diagnosis','MedicationID','DoseNumber','FirstDose','PrimaryNurse','ArrivalStatus','TreatmentStatus','LabsStatus','ConsentStatus','SickLeave','WatcherLeave','HomeMedicationRefill','NextAppointmentDate','Notes','PatientID','CreatedBy','CreatedAt'],
'Booking Requests':['RequestID','MRN','PatientName','MedicationID','Specialty','Consultant','DoseNumber','FirstDose','RequestedAppointmentDate','AlternativeDate','FinalAppointmentDate','Reason','RequestStatus','BookingType','PreviousBookingID','PreviousAppointmentDate','CreatedBy','CreatedAt'],
'Booking Data':['BookingID','RequestID','MRN','PatientName','MedicationID','Specialty','Consultant','DoseNumber','FirstDose','AppointmentDate','BookingStatus','BookingType','PreviousBookingID','PreviousAppointmentDate','CreatedBy','CreatedAt','ModifiedBy','ModifiedAt','ChangeReason'],
'Change Requests':['ChangeID','MRN','PreviousBookingID','PreviousAppointmentDate','RequestedNewDate','FinalNewDate','ChangeReason','ChangeStatus','CreatedBy','CreatedAt'],
'Waiting List':['WaitingID','RequestID','MRN','MedicationID','RequestedDate','Status','Reason','ConfirmedBy','ConfirmedAt','CreatedAt'],
'No Arrival Log':['NoArrivalID','BookingID','MRN','AppointmentDate','Status','CreatedAt','ClosedAt'],
'Medication Master':['MedicationID','GenericName','BrandNamesAliases','ItemType','Route','BookingCategory','AdministrationType','ExpectedChairMinutes','ObservationMinutes','WeekendEligibility','DailyLimit','RequiresFormB','DefaultNoNextAppointment','IsActive'],
'Medication Aliases':['AliasID','MedicationID','Alias','IsActive'],
'Treatment Schedules':['ScheduleID','MedicationID','ScheduleNameArabic','ScheduleNameEnglish','Phase','DoseSequenceFrom','DoseSequenceTo','IntervalNumber','IntervalUnit','MaximumLoadingDoses','NoNextAppointment','RequiresFormB','IsActive','ApprovedBy','ApprovedAt','Version'],
'Specialty Master':['SpecialtyID','NameEnglish','NameArabic','Icon','IsActive'],
'Consultant Master':['ConsultantID','ConsultantName','Specialty','IsActive'],
'Capacity Rules':['RuleID','DayType','MedicationID','ItemType','RuleType','Limit','IsActive','ApprovedBy','ApprovedAt'],
'Closed Dates':['Date','Reason','IsActive'],
'Users Roles':['Email','Role','Specialties','CanViewMRN','CanViewMobile','IsActive'],
'Daily Huddle':['HuddleID','Date','PayloadJson','CreatedAt'],
'Audit Log':['AuditID','ActorEmail','Action','Entity','EntityID','OldValue','NewValue','Reason','CreatedAt'],
'System Config':['Key','Value','UpdatedAt']};
function installSystem(){var props=PropertiesService.getScriptProperties(); var id=props.getProperty('DCU_SPREADSHEET_ID'); var ss=id?SpreadsheetApp.openById(id):SpreadsheetApp.create('DCU Booking Book 2026-2027'); props.setProperty('DCU_SPREADSHEET_ID',ss.getId()); Object.keys(TABLE_HEADERS).forEach(function(n){SheetRepository.ensureSheet(n,TABLE_HEADERS[n]);}); seedReferenceData_(); createMonthlySheets_(); createTriggers(); migrateSystem();}
function migrateSystem(){var ss=SheetRepository.ss(); ss.copy('DCU Backup before migrate '+new Date().toISOString()); Object.keys(TABLE_HEADERS).forEach(function(n){SheetRepository.ensureSheet(n,TABLE_HEADERS[n]);}); upsertConfig_('SchemaVersion','1'); AuditService.log('MIGRATE','System Config','SchemaVersion',null,{version:'1'},'safe migration');}
function seedReferenceData_(){if(SheetRepository.readTable(DCU.SHEETS.MED).length===0){DCU.MEDS.forEach(function(m){var o={}; TABLE_HEADERS[DCU.SHEETS.MED].forEach(function(h,i){o[h]=m[i];}); SheetRepository.appendRow(DCU.SHEETS.MED,o);});} if(SheetRepository.readTable(DCU.SHEETS.SPEC).length===0){DCU.SPECIALTIES.forEach(function(s){SheetRepository.appendRow(DCU.SHEETS.SPEC,{SpecialtyID:s[0],NameEnglish:s[0],NameArabic:s[1],Icon:s[2],IsActive:'Yes'});});} if(SheetRepository.readTable(DCU.SHEETS.CAP).length===0){[['Weekend','MED_IRON_SUCROSE','','MedicationLimit',10],['Weekend','MED_FERINJECT','','MedicationLimit',10],['Weekend','','','DailyLimit',20],['Weekend','','','FirstDoseLimit',2],['Weekday','','','DailyLimit',20],['Weekday','','Procedure','ProcedureLimit',2],['Weekday','MED_IVIG','','MedicationLimit',2],['Weekday','MED_DESFERAL','','MedicationLimit',2],['Weekday','MED_BLOOD','','MedicationLimit',2],['Weekday','','','FirstDoseLimit',2]].forEach(function(r){SheetRepository.appendRow(DCU.SHEETS.CAP,{RuleID:Utilities.getUuid(),DayType:r[0],MedicationID:r[1],ItemType:r[2],RuleType:r[3],Limit:r[4],IsActive:'Yes',ApprovedBy:'LOCAL_ADMIN_REQUIRED',ApprovedAt:''});});} upsertConfig_('SystemMode','SETUP');}
function upsertConfig_(k,v){var rows=SheetRepository.readTable(DCU.SHEETS.CONFIG), r=rows.filter(function(x){return x.Key===k;})[0]; if(r) SheetRepository.updateRow(DCU.SHEETS.CONFIG,r.sheetRowNumber,{Value:v,UpdatedAt:new Date()}); else SheetRepository.appendRow(DCU.SHEETS.CONFIG,{Key:k,Value:v,UpdatedAt:new Date()});}
function createMonthlySheets_(){var ss=SheetRepository.ss(); DcuLogic.monthSheets().forEach(function(m){var sh=ss.getSheetByName(m.name)||ss.insertSheet(m.name); if(sh.getLastRow()===0){sh.getRange(1,1,1,8).setValues([['No','Patient Name','MRN','Mobile No','Diagnosis / Medication','Appointment / Readmission Date','Doctor','Rebooking Date']]); sh.setFrozenRows(1); for(var d=1,row=2;d<=m.days;d++,row++){sh.getRange(row,1).setValue(m.name+' '+String(d).padStart(2,'0'));}}});}
function validateReadiness(){var report=[]; function add(ok,code,msg){report.push({ok:ok,code:code,message:msg});} try{SheetRepository.ss(); add(true,'SPREADSHEET_ID','Spreadsheet configured');}catch(e){add(false,'SPREADSHEET_ID','Set DCU_SPREADSHEET_ID in Script Properties');} var users=[]; try{users=SheetRepository.readTable(DCU.SHEETS.USERS);}catch(e){} add(users.some(function(u){return u.Role==='Admin'&&u.IsActive==='Yes';}),'ADMIN_USER','Active Admin required'); add(SheetRepository.readTable(DCU.SHEETS.CAP).length>0,'CAPACITY_RULES','Capacity rules present and must be locally approved'); add(SheetRepository.readTable(DCU.SHEETS.MED).length>=30,'MEDICATION_MASTER','Medication master present; pharmacy review required'); add(users.length>0,'USERS_ROLES','Users roles populated'); add(DcuLogic.monthSheets().every(function(m){var sh=SheetRepository.ss().getSheetByName(m.name); return sh&&m.days===DcuLogic.monthSheets().filter(function(x){return x.name===m.name;})[0].days;}),'MONTH_SHEETS','24 monthly sheets present'); add(ConfigService.getMode()==='LIVE','SYSTEM_MODE','Admin must set SystemMode LIVE after review'); return report;}
