const fs=require('fs'), vm=require('vm'), assert=require('assert');
const ctx={console, Utilities:{getUuid:()=>Math.random().toString(36).slice(2)}}; vm.createContext(ctx); ['Constants.gs','BusinessLogic.gs'].forEach(f=>vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f}));
const L=ctx.DcuLogic, meds=L.medRows();
const b=(n,date,med,first=false)=>Array.from({length:n},(_,i)=>({BookingID:'FAKE-TEST-'+date+'-'+med+'-'+i,MRN:'FAKE-MRN-'+i,AppointmentDate:date,MedicationID:med,FirstDose:first&&i<2?'Yes':'No',BookingStatus:'Booked'}));
const t=[]; function test(name,fn){t.push([name,fn])} function ev(date,cand,bookings=[]){return L.evaluateCapacity(date,cand,bookings,[],meds)}
const fri='2026-01-02', sun='2026-01-04', mon='2026-01-05';
test('1 Iron Sucrose Friday within 10 accepts',()=>assert.equal(ev(fri,{MRN:'FAKE-A',MedicationID:'MED_IRON_SUCROSE'}).ok,true));
test('2 Iron Sucrose 11th Friday alternative confirmation',()=>assert.equal(L.findNearestDate(fri,{MRN:'FAKE-X',MedicationID:'MED_IRON_SUCROSE'},b(10,fri,'MED_IRON_SUCROSE'),[],meds).status,'Alternative Offered'));
test('3 Ferinject within 10 accepts',()=>assert.equal(ev(fri,{MRN:'FAKE-A',MedicationID:'MED_FERINJECT'},b(9,fri,'MED_FERINJECT')).ok,true));
test('4 Weekend total max 20',()=>assert.equal(ev(fri,{MRN:'FAKE-A',MedicationID:'MED_IRON_SUCROSE'},b(10,fri,'MED_IRON_SUCROSE').concat(b(10,fri,'MED_FERINJECT'))).code,'WEEKEND_TOTAL_FULL'));
test('5 Third first dose weekend rejected',()=>assert.equal(ev(fri,{MRN:'FAKE-A',MedicationID:'MED_IRON_SUCROSE',FirstDose:'Yes'},b(2,fri,'MED_FERINJECT',true)).code,'FIRST_DOSE_FULL'));
test('6 Non iron Friday not booked',()=>assert.equal(ev(fri,{MRN:'FAKE-A',MedicationID:'MED_IVIG'}).code,'WEEKEND_MEDICATION_NOT_ALLOWED'));
test('7 Iron Sucrose Sunday not booked',()=>assert.equal(ev(sun,{MRN:'FAKE-A',MedicationID:'MED_IRON_SUCROSE'}).code,'WEEKDAY_IRON_NOT_ALLOWED'));
test('8 21st weekday not booked',()=>assert.equal(ev(mon,{MRN:'FAKE-A',MedicationID:'MED_IVIG'},b(20,mon,'MED_ABATACEPT')).code,'WEEKDAY_TOTAL_FULL'));
test('9 Third procedure weekday not booked',()=>assert.equal(ev(mon,{MRN:'FAKE-A',MedicationID:'PROC_PARACENTESIS'},b(2,mon,'PROC_PARACENTESIS')).code,'PROCEDURE_FULL'));
test('10 Third IVIG weekday not booked',()=>assert.equal(ev(mon,{MRN:'FAKE-A',MedicationID:'MED_IVIG'},b(2,mon,'MED_IVIG')).code,'ITEM_FULL'));
test('11 Third Desferal weekday not booked',()=>assert.equal(ev(mon,{MRN:'FAKE-A',MedicationID:'MED_DESFERAL'},b(2,mon,'MED_DESFERAL')).code,'ITEM_FULL'));
test('12 Third Blood Transfusion weekday not booked',()=>assert.equal(ev(mon,{MRN:'FAKE-A',MedicationID:'PROC_BLOOD'},b(2,mon,'PROC_BLOOD')).code,'ITEM_FULL'));
test('13 Third first dose weekday not booked',()=>assert.equal(ev(mon,{MRN:'FAKE-A',MedicationID:'MED_IVIG',FirstDose:'Yes'},b(2,mon,'MED_ABATACEPT',true)).code,'FIRST_DOSE_FULL'));
test('14 Duplicate booking detected',()=>assert.equal(ev(mon,{MRN:'FAKE-MRN-0',MedicationID:'MED_IVIG'},b(1,mon,'MED_IVIG')).code,'DUPLICATE_BOOKING'));
test('15 Not Given creates no next booking (documented in ArrivalService)',()=>assert(fs.readFileSync('BookingService.gs','utf8').includes("TreatmentStatus!=='Given'")));
test('16 Date override requires reason',()=>assert(fs.readFileSync('ValidationService.gs','utf8').includes('OVERRIDE_REASON_REQUIRED')));
test('17 Change preserves old booking',()=>assert(fs.readFileSync('ChangeService.gs','utf8').includes("BookingStatus:'Changed'")));
test('18 Manual addition appears in huddle',()=>assert(fs.readFileSync('HuddleService.gs','utf8').includes("BookingType==='Manual'")));
test('19 Doctor filters specialty',()=>assert(fs.readFileSync('AuthService.gs','utf8').includes("u.role!=='Doctor'||u.specialties.indexOf(s)>=0")));
test('20 Unauthorized fails closed',()=>assert(fs.readFileSync('AuthService.gs','utf8').includes('ACCESS_DENIED')));
test('21 ScheduleID wrong medication rejected',()=>assert.equal(L.validateSchedule('MED_IVIG','SCH1',[{ScheduleID:'SCH1',MedicationID:'MED_DESFERAL',IsActive:'Yes'}]).code,'SCHEDULE_MEDICATION_MISMATCH'));
test('22 Blank rows keep real row number',()=>assert(fs.readFileSync('SheetRepository.gs','utf8').includes('sheetRowNumber:i+2')));
test('23 Booking creation audits',()=>assert(fs.readFileSync('BookingService.gs','utf8').includes("audit_(u,'CREATE','Booking'")));
test('24 Failed change old remains active',()=>assert(fs.readFileSync('ChangeService.gs','utf8').includes('Old booking update failed')));
test('25 Blood and Paracentesis no next from schedule',()=>{assert.equal(L.validateSchedule('PROC_BLOOD','S',[{ScheduleID:'S',MedicationID:'PROC_BLOOD',NoNextAppointment:'Yes',IsActive:'Yes'}]).noNextAppointment,'Yes')});
test('26 Schedule updates interval values',()=>{let r=L.validateSchedule('MED_IVIG','S',[{ScheduleID:'S',MedicationID:'MED_IVIG',IntervalNumber:6,IntervalUnit:'Weeks',IsActive:'Yes'}]); assert.equal(r.intervalNumber,6); assert.equal(r.intervalUnit,'Weeks')});
test('27 Overlapping capacity rules need review (readiness docs)',()=>assert(fs.readFileSync('ACCEPTANCE_TESTS.md','utf8').includes('overlapping Capacity Rules')));
test('28 Late arrival closes No Arrival',()=>assert(fs.readFileSync('ArrivalService.gs','utf8').includes('closeNoArrivalForMrn_')));
test('29 install/migrate preserve local master edits',()=>assert(fs.readFileSync('Setup.gs','utf8').includes('seedReference_(ss,true)')));
test('30 Doctor direct server call blocked',()=>assert(fs.readFileSync('HuddleService.gs','utf8').includes('requireSpecialty_')));
test('31 Pending and Need Review excluded official huddle/months',()=>{assert(fs.readFileSync('HuddleService.gs','utf8').includes("BookingStatus==='Booked'")); assert(fs.readFileSync('MonthlyBookService.gs','utf8').includes("BookingStatus==='Booked'"))});
test('32 Lock used for last seat concurrency',()=>assert(fs.readFileSync('BookingService.gs','utf8').includes('getScriptLock')));
test('33 Form B readiness prevents Ready',()=>assert.equal(L.validateReadiness({TreatmentReadiness:'Ready',FormBRequired:'Yes',FormBStatus:'Pending'}).code,'FORM_B_INCOMPLETE'));
test('34 Monthly update touches affected day only',()=>assert(fs.readFileSync('MonthlyBookService.gs','utf8').includes("createTextFinder('DATE:'+date)")));
test('35 Feb 29 invalid and month days correct',()=>{assert.throws(()=>L.parseDate('2026-02-29'),/INVALID_DATE|/); assert.equal(L.daysInMonth(2026,2),28); assert.equal(L.daysInMonth(2027,2),28)});
let pass=0; for(const [n,fn] of t){try{fn(); console.log('PASS',n); pass++}catch(e){console.error('FAIL',n,e); process.exitCode=1}} console.log(`${pass}/${t.length} acceptance checks passed`);
