const assert=require('assert'); const logic=require('../Logic.js').DcuLogic;
const meds=[['MED_IRON_SUCROSE','Medication'],['MED_FERINJECT','Medication'],['MED_IVIG','Medication'],['MED_DESFERAL','Medication'],['MED_BLOOD','Blood Product'],['MED_ABATACEPT','Medication'],['PROC_PARACENTESIS','Procedure']].map(x=>({MedicationID:x[0],ItemType:x[1],IsActive:'Yes'}));
function b(n,date,med,extra={}){return {BookingID:'B'+n,MRN:'T-'+n,AppointmentDate:date,MedicationID:med,BookingStatus:'Booked',FirstDose:extra.first?'Yes':'No'};}
function ok(name,fn){try{fn(); console.log('PASS',name)}catch(e){console.error('FAIL',name,e); process.exitCode=1}}
const fri='2026-01-02', sun='2026-01-04', mon='2026-01-05';
ok('1 Iron Sucrose Friday within 10 accepts',()=>assert.equal(logic.validateCapacity({date:fri,mrn:'X1',medicationId:'MED_IRON_SUCROSE'},[],meds,[],[]).ok,true));
ok('2 Iron Sucrose 11th Friday moves and needs confirmation',()=>{let bs=Array.from({length:10},(_,i)=>b(i,fri,'MED_IRON_SUCROSE')); let r=logic.findNextAvailable({date:fri,mrn:'X11',medicationId:'MED_IRON_SUCROSE'},bs,meds,[],[]); assert.equal(r.requiresConfirmation,true); assert.notEqual(r.date,fri)});
ok('3 Ferinject within 10 accepts',()=>assert.equal(logic.validateCapacity({date:fri,mrn:'F1',medicationId:'MED_FERINJECT'},[],meds,[],[]).ok,true));
ok('4 Weekend total not over 20',()=>{let bs=Array.from({length:20},(_,i)=>b(i,fri,i<10?'MED_IRON_SUCROSE':'MED_FERINJECT')); assert.equal(logic.validateCapacity({date:fri,mrn:'X21',medicationId:'MED_FERINJECT'},bs,meds,[],[]).code,'DAILY_FULL')});
ok('5 Weekend third first dose rejected',()=>{let bs=[b(1,fri,'MED_IRON_SUCROSE',{first:true}),b(2,fri,'MED_FERINJECT',{first:true})]; assert.equal(logic.validateCapacity({date:fri,mrn:'X3',medicationId:'MED_IRON_SUCROSE',firstDose:true},bs,meds,[],[]).code,'FIRST_DOSE_FULL')});
ok('6 Non-iron Friday not booked',()=>assert.equal(logic.validateCapacity({date:fri,mrn:'N',medicationId:'MED_IVIG'},[],meds,[],[]).code,'WEEKEND_MEDICATION_NOT_ALLOWED'));
ok('7 Iron Sucrose Sunday not booked',()=>assert.equal(logic.validateCapacity({date:sun,mrn:'I',medicationId:'MED_IRON_SUCROSE'},[],meds,[],[]).code,'WEEKDAY_IRON_NOT_ALLOWED'));
ok('8 21st weekday patient not booked',()=>{let bs=Array.from({length:20},(_,i)=>b(i,mon,'MED_ABATACEPT')); assert.equal(logic.validateCapacity({date:mon,mrn:'P21',medicationId:'MED_ABATACEPT'},bs,meds,[],[]).code,'DAILY_FULL')});
ok('9 Third procedure weekday not booked',()=>{let bs=[b(1,mon,'PROC_PARACENTESIS'),b(2,mon,'MED_BLOOD')]; assert.equal(logic.validateCapacity({date:mon,mrn:'P3',medicationId:'PROC_PARACENTESIS'},bs,meds,[],[]).code,'PROCEDURE_FULL')});
ok('10 IVIG third weekday not booked',()=>{let bs=[b(1,mon,'MED_IVIG'),b(2,mon,'MED_IVIG')]; assert.equal(logic.validateCapacity({date:mon,mrn:'I3',medicationId:'MED_IVIG'},bs,meds,[],[]).code,'MEDICATION_DAILY_FULL')});
ok('11 Desferal third weekday not booked',()=>{let bs=[b(1,mon,'MED_DESFERAL'),b(2,mon,'MED_DESFERAL')]; assert.equal(logic.validateCapacity({date:mon,mrn:'D3',medicationId:'MED_DESFERAL'},bs,meds,[],[]).code,'MEDICATION_DAILY_FULL')});
ok('12 Blood third weekday not booked',()=>{let bs=[b(1,mon,'MED_BLOOD'),b(2,mon,'MED_BLOOD')]; assert.equal(logic.validateCapacity({date:mon,mrn:'B3',medicationId:'MED_BLOOD'},bs,meds,[],[]).code,'MEDICATION_DAILY_FULL')});
ok('13 First dose third weekday not booked',()=>{let bs=[b(1,mon,'MED_IVIG',{first:true}),b(2,mon,'MED_DESFERAL',{first:true})]; assert.equal(logic.validateCapacity({date:mon,mrn:'F3',medicationId:'MED_ABATACEPT',firstDose:true},bs,meds,[],[]).code,'FIRST_DOSE_FULL')});
ok('14 duplicate booking prevented',()=>assert.equal(logic.validateCapacity({date:mon,mrn:'DUP',medicationId:'MED_ABATACEPT'},[{MRN:'DUP',AppointmentDate:mon,MedicationID:'MED_ABATACEPT',BookingStatus:'Booked'}],meds,[],[]).code,'DUPLICATE_BOOKING'));
ok('21 ScheduleID wrong medication rejected',()=>assert.throws(()=>logic.validateSchedule({IsActive:'Yes',MedicationID:'MED_IVIG'},'MED_DESFERAL'),/SCHEDULE_MEDICATION_MISMATCH/));
ok('25 no next appointment true preserved',()=>assert.equal(logic.validateSchedule({IsActive:'Yes',MedicationID:'MED_BLOOD',NoNextAppointment:'Yes'},'MED_BLOOD').NoNextAppointment,true));
ok('26 new schedule updates interval',()=>assert.deepEqual(logic.validateSchedule({IsActive:'Yes',MedicationID:'MED_IVIG',IntervalNumber:'6',IntervalUnit:'Weeks'},'MED_IVIG'),{IntervalNumber:'6',IntervalUnit:'Weeks',NoNextAppointment:false}));
ok('27 overlapping rules error',()=>assert.throws(()=>logic.validateCapacity({date:mon,mrn:'X',medicationId:'MED_ABATACEPT'},[],meds,[],[{IsActive:'Yes',DayType:'Weekday',RuleType:'DailyLimit'},{IsActive:'Yes',DayType:'Weekday',RuleType:'DailyLimit'}]),/Overlapping/));
ok('31 pending need review excluded by monthly/huddle predicate concept',()=>{let official=[{BookingStatus:'Booked'},{BookingStatus:'Pending'},{BookingStatus:'Need Review'}].filter(x=>x.BookingStatus==='Booked'); assert.equal(official.length,1)});
ok('33 Form B required blocks readiness',()=>assert.equal(logic.validateReadiness({FormBRequired:'Yes',FormBStatus:'Pending',TreatmentReadiness:'Ready'},'2026-01-01').ready,false));
ok('35 Feb 29 rejected and month days correct',()=>{assert.equal(logic.validateCapacity({date:'2026-02-29',mrn:'X',medicationId:'MED_IVIG'},[],meds,[],[]).code,'DATE_OUT_OF_RANGE'); let feb=logic.monthSheets().filter(x=>x.name==='2026 February')[0]; assert.equal(feb.days,28)});
